export enum TipoNotificacionEnum {
  SOLICITUD_CAMBIO_ROL = 'SOLICITUD_CAMBIO_ROL',
  RESPUESTA_CAMBIO_ROL = 'RESPUESTA_CAMBIO_ROL',
  CAMBIO_ROL = 'CAMBIO_ROL',
  MENSAJE_GENERAL = 'MENSAJE_GENERAL'
}
