export enum EstadoLogin {
    ESPERANDO = 'ESPERANDO_CREDENCIAL',
    OK = 'OK',
    CREDENCIALES_INVALIDAS = 'CREDENCIALES_INVALIDAS',
    CUENTA_INACTIVA = 'CUENTA_INACTIVA',
    CAMBIAR_PASS = 'CAMBIAR_PASS'
}
